name: Build & Publish Release
on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build-images:
    name: Build Images
    uses: ./.github/workflows/build_image.yml
    secrets: inherit

  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Build and publish in parallel: linux/amd64, linux/arm64
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(git describe --tags --exclude 'nats-k8s-based-resolver-*') >> ${GITHUB_ENV}

      - uses: wangyoucao577/go-release-action@v1.53
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: '1.24.4'
          binary_name: 'nats-k8s-based-resolver'
          project_path: ./cmd
          extra_files: LICENSE README.md VERSION
          ldflags: '-X github.com/zerbytes/nats-k8s-based-resolver/pkg/version.Version=${{ env.APP_VERSION }}'
